In [ ]:
#1.1
import numpy as np
a=np.array(input().split( ), dtype=int)
d={}
c=0
for i in a:
  if i not in d:
    d[i]=1
    c+=1
print(c)

6 2 85 25 1 32 54 6 85 2
7


In [ ]:
#1.2
import numpy as np
a=np.array([1, -1, 3, 2, -7, -5, 11, 6])
l1=[]
l2=[]
for i in a:
  if i>0:
    l1.append(i)
  else:
    l2.append(i)
l=l1+l2
l

[1, 3, 2, 11, 6, -1, -7, -5]

In [ ]:
#1.3
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
N = 10
S = 15
c=0
p=-1
for i in range(N):
  p+=1
  if c==S:
    break
  else:
    for j in range(p,N):
      c+=a[j]
      if c>S:
        c=0
        break
      elif c==S:
        print(p+1,j+1)
        break

1 5


In [ ]:
#1.4
import numpy as np
a=np.array([1, 1, 1, 1, 1])
N=5
x=1
f=0
for i in a:
  if i==x:
    f+=1
print(f)

5


In [ ]:
#1.5
import numpy as np
a=np.array([7, 10, 4, 3, 20, 15])
a.sort()
K = 3
print(a[K-1])

7


In [ ]:
#1.6
import numpy as np
a=np.array([0, 2, 1, 2, 0])
a.sort()
print(a)

[0 0 1 2 2]


In [ ]:
#1.7
import numpy as np
a=np.array([3,0,0,2,0,4] )
N=6
if a[0]>a[-1]:
  s=a[-1]
else:
  s=a[0]
b=0
for i in a:
  if i<=s:
    b+=i
print((N-2)*s-b)

7


In [ ]:
#1.8
import numpy as np
a=np.array([1,2,3,4,5])
n=5
l=[]
for i in a:
  l.append(i)
for i in range(1,len(l)):
  l[i],l[i-1]=l[i-1],l[i]
print(np.array(l))

[2 3 4 5 1]


In [ ]:
#1.9
import numpy as np
a=np.array([3,1,3,3,2])
d={}
c=0
for i in a:
  if i not in d:
    d[i]=0
  else:
    d[i]+=1
  if d[i]<c:
    c=i
print(i)

2


In [ ]:
#1.10
import numpy as np
a=np.array([1, 3, 5, 8, 9, 2, 6, 7, 6, 8, 9])
N=11
s=0
j=0
for i in range(N):
  if s==i:
    s+=a[i]
    j+=1
print(j)

3


In [ ]:
#1.11
import numpy as np
a=np.array([3, 9, 12, 16, 20] )
N=5
k=3
for i in range(N):
  if i<k:
    a[i]+=k
  else:
    a[i]-=k
d=a[-1]-a[0]
print(d,a)

11 [ 6 12 15 13 17]


In [ ]:
#1.12
import numpy as np
a=np.array([900, 940, 950, 1100, 1500, 1800])
d=np.array([910, 1200, 1120, 1130, 1900, 2000])
n=6
p = 1
m= 1
i = 1
j = 0
while i < n and j < n:
  if a[i] <= d[j]:
    p+= 1
    i += 1
    if m<p:
      m=p
  else:
    p-= 1
    j += 1
print(m)

3


In [ ]:
#1.13
import numpy as np
a=np.array([3, 4, 1, 9, 56, 7, 9, 12])
a.sort()
print(a)
N = 8
M = 5
md=a[-1]-a[0]
for i in range(N-M+1):
  d=a[i+M-1]-a[i]
  print(d)
  if d<md:
    md=d
print(md)

[ 1  3  4  7  9  9 12 56]
8
6
8
49
6


In [ ]:
#1.14
import numpy as np
a=np.array([2,6,1,9,4,5,3])
a.sort()
for i in range(len(a)):
  if a[i]!=a[i+1]:
    print(a[i])
    break

1


In [ ]:
#1.15
import numpy as np
a1=np.array([1,2])
a2=np.array([3,4])
a=np.concatenate((a1,a2))
a.sort()
if len(a)%2!=0:
  print(a[(len(a)-1)//2])
else:
  n1=a[(len(a)-2)//2]
  n2=a[((len(a)-2)//2)+1]
  print((n1+n2)/2)

2.5
