In [ ]:
print('"hello world"')
print(" \" hello world \" ")
print('hello world \nhello world')
print('hello world',end='')
print('helloworld')
# '\n' to separate one line into two
# ,end='' to join two line into one
print('hello'  +  'world')
print('hellow'   ,    'world')
#f-string
x=0
print(f'aaaaa{x}aaaaa')

"hello world"
 " hello world " 
hello world 
hello world
hello worldhelloworld
helloworld
hellow world


In [ ]:
print('hello ' + input('what is your name? '))

what is your name: Boss
hello Boss


In [ ]:
len(input('what is your name? '))


what is your name? boss boss


9

In [ ]:
#replacing the value
a=3
b=7
c=a
a=b
b=c
print('a=', a , '\n''b=', b )

a= 7 
b= 3


In [ ]:
# Data type basic
#String- str()
'hellow'[0]   # [position]
#Integer- int()
12345
#Floating- float()
123.456
#Boolean- bool()
True
False
type() # it checks the typr of data
#string.isnumeric().upper().lower().count().find().replace().strip().split(',')
#floating.format()

In [ ]:
print(round(8/3,2)) # to round up/down to specific digit
print(11//99) # divides and round down
# small%big=small , big%small=remainder , small//big=0, big//small=divide down

2.67
0


In [ ]:
if   #if the condition is met then program goes to it
elif #if the above 'if' or 'elif' condition is met then this condition is not checked
else #if none of the above conditions under the last 'if' are met then program passes theough it

In [ ]:
import random
r= random.randint(0,10) #(stop,stope-1)
m= random.randrange(1,100,10)#(stop,stope-1,step)
n= random.random() #0-1
s= random.shuffle()#shuffle the order
c= random.choice()#choice one item
print(r,m,n)

1 41 0.8347738925607598


In [ ]:
List= ['a','b','c','d','e']
#List[position](0to4)(-1to-5)
List.append().extend().insert(position,item).remove().pop().popleft().popright().count().sort().reverse()
#list with in a list , nested list
#add list , l= l1 + l2

In [ ]:
range(start,stop-1,step) , range(n)#(0 to n-1)
#for i in str/range/list : (good iteration)
#while condition : (good for certain condition)

In [ ]:
import numpy as np
ar=np.array([value]) #given array
np.zeros(size, dtype = datatype) #dtype defult float
np.one((row,col),dtype = datatype)
np.empty((row,col),dtype)
np.full((row,col), given ele) # every element in the array is fill with given ele
#ar.shape=(row,col)
#ar.size=no. of element
row=len(ar)
col=len(ar[0])

# not much important below this for this cell

ar.astype(new datatype) # to change the datatype
arc=ar.copy() # to coppy array
ars=ar.reshape() # change the shape of array, -1 to flatten array

np.nditer(ar[::], flags=['buffered'], op_dtypes=['new datatype']) # iterats through all element, slicing or fl&op is optional
np.ndenumerate(ar) # gives index and element in loop

arj=np.concatenate((a1,a2)axis).stack().hstack().vstack().dstack() # join array
ars=np.array_split(ar, parts, axis) # splits in equal parts

aw=np.where(ar==ele) # makes an array where the elements are the index of ele
ass=np.searchsorted(ar, ele, side='') # returns the index of 1st ele

np.sort(ar) # sorts numarically and alphabetically in 1st dimention

In [ ]:
import numpy as np # importing
a=np.array([1,2,3,4,5,6,7,8,9]) # creating
print(a) #calling
print(a[0]) # indexing (negative possible)
print(a[1:9:2]) # slicing [start:end:gap] (negative possible)

[1 2 3 4 5 6 7 8 9]
1
[2 4 6 8]


In [ ]:
a2d=np.array([[1,2,3],
              [4,5,6]]) # 2D array

a3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]],
              [[1,2,3],[4,5,6],[7,8,9]]]) # 3D array

print(a2d)
print(a3d)

a4d=np.array([1, 2, 3, 4], ndmin=4) # to define the dimention
print(a4d.ndim) # to check the dimention of array
print(a4d.shape) # to know how many element in each dimention

print(a3d[1][1][1]) # indexing
print(a3d[0:1][1:2][2:3]) # slicing can also be used within indexing

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
4 (1, 1, 1, 4)
5
[]
